Tabelle Keepers
xdoo/lhm_animad_admin_html5 pull request #5
Opened 2017-11-16 14:41 UTC by ejcsid

- Anzeige der Liste
- Löschen von Datensätzen aus Liste (Liste wird noch nicht aktualisiert)

2017-11-16 15:43 UTC, xdoo requested changes
Ich habe da noch ein paar offene Punkte. Bitte nochmal drüber schauen. Danke :)

2017-11-16 15:43 UTC, xdoo commented on src/animad-keeper/animad-keepers-list.html
> +      HTMLImports.whenReady(function() {
Warum machst du das hier nicht mit 

class AnimadKeepersList extends Polymer.Element {
...
}

2017-11-16 15:43 UTC, xdoo commented on src/animad-keeper/animad-keepers-create-form.html
> +<dom-module id="animad-keepers-list">
Warum heißt dieses Element 'animad-keepers-list'? Sollte das nicht 'animad-keepers-create-form' heißen? Ich würde das auch raus nehmen. Das führt zu Konflikten.

2017-11-16 15:43 UTC, xdoo commented on src/animad-keeper/animad-keepers-create-form.html
> +        class AnimadKeepersList extends Polymer.Element {
Siehe oben.

2017-11-16 15:43 UTC, xdoo commented on src/animad-keeper/animad-keepers-list.html
> +            @apply(--layout-fullbleed); /* height: 100vh; margin: 0 */
Was macht dieses @apply hier? Ein Mixin definiert man über @apply --layout-fullbleed. Füllen muss man das aber an anderer Stelle. Die Kommentare machen für mich keinen Sinn.

2017-11-16 15:43 UTC, xdoo commented on src/animad-keeper/animad-keepers-list.html
> +            @apply(--layout-vertical); /* display: flex; flex-direction: column; */
siehe oben

2017-11-16 15:43 UTC, xdoo commented on src/animad-keeper/animad-keepers-list.html
> +            @apply(--layout-flex-auto); /* flex: 1 1 auto; */
siehe oben

2017-11-17 12:21 UTC, xdoo commented
Die Datei src/animad-keepers-view.html erzeugt einen Konflikt. Den bitte lösen.

Du hast immer noch die Datei src/animad-keeper/animad-keepers-create-form.html drin und diese aber in `<dom-module id="animad-keepers-list">` umbenannt. Die wird danach nicht mehr funktionieren. Das bitte noch ändern.

2017-11-17 12:47 UTC, ejcsid commented
Hoffe, es ist jetzt ok?

2017-11-17 12:54 UTC, xdoo commented
Die Datei `src/animad-keeper/animad-keepers-create-form.html` schon, aber es sind immer noch Konflikte drin. Bitte einen Pull auf mein Repo machen, die Konflikte lösen und dann nochmal den pull request auslösen.

2017-11-20 10:09 UTC, merged